use std::{
    fs,
    path::PathBuf,
    process::{ExitCode, exit},
};
use toml::{Value, map::Map};

#[cfg(any(target_os = "macos", target_os = "linux"))]
pub const DEFAULT_PREFIX: &str = "/opt/packit/test";

#[cfg(target_os = "windows")]
pub const DEFAULT_PREFIX: &str = "C:\\Program Files\\packit\\test";

#[cfg(target_os = "linux")]
pub const DEFAULT_CONFIG_DIR: &str = "/etc/packit";

#[cfg(target_os = "macos")]
pub const DEFAULT_CONFIG_DIR: &str = "/Library/Application Support/packit";

#[cfg(target_os = "windows")]
pub const DEFAULT_CONFIG_DIR: &str = "C:\\Program Files\\packit";

struct Cleanup {
    existing_config: bool,
}

// Implement drop to make sure the cleanup is still ran, even if a test panics
impl Drop for Cleanup {
    fn drop(&mut self) {
        // TODO
    }
}

fn main() -> ExitCode {
    // Execute setup, which will partially determine how the cleanup
    let _cleanup = setup();

    let status = std::process::Command::new("cargo")
        .args(["test", "--features", "test-support", "--", "--test-threads=1"])
        .status()
        .expect("failed to run cargo test");

    ExitCode::from(status.code().unwrap_or(1) as u8)
}

fn setup() -> Cleanup {
    let mut cleanup = Cleanup { existing_config: true };
    let config_dir = PathBuf::from(DEFAULT_CONFIG_DIR).join("TestConfig.toml");
    if !fs::exists(&config_dir).unwrap() {
        create_default_test_config(&config_dir);
        cleanup.existing_config = true;
    }

    // Get test config content
    let config_content = fs::read_to_string(&config_dir).unwrap();
    let config_content: Value = toml::from_str(&config_content).unwrap();
    let config_content = config_content.as_table().unwrap();

    let Some(prefix) = config_content.get("prefix_directory") else {
        println!("Couldn't find 'prefix_directory' in 'TestConfig.toml'");
        exit(1);
    };

    let Some(prefix) = prefix.as_str() else {
        println!("Invalid string value for 'prefix_directory' in 'TestConfig.toml'");
        exit(1);
    };

    let prefix = PathBuf::from(prefix);

    // Return an error if the prefix already exists, this could mean it's a 'normal' Packit prefix
    if fs::exists(&prefix).unwrap() {
        println!("Test prefix '{}' specified in 'TestConfig.toml' already exists", prefix.display());
        exit(1);
    }

    let register_directory = prefix.join("Register.toml");
    println!("Using prefix: {}", prefix.display());
    fs::create_dir_all(prefix).unwrap();
    fs::write(register_directory, "# DO NOT EDIT THIS FILE").unwrap();

    cleanup
}

fn create_default_test_config(config_dir: &PathBuf) {
    fs::create_dir_all(config_dir).unwrap();

    let mut config = Map::new();
    config.insert("repositories_rank".into(), Value::Array(vec!["test".into()]));

    let mut repositories = Map::new();
    let mut test_repository = Map::new();
    test_repository.insert(
        "url".into(),
        Value::String("https://raw.githubusercontent.com/pack-it/test-repository/main/".into()),
    );
    test_repository.insert("provider".into(), "fs".into());

    repositories.insert("test".into(), Value::Table(test_repository)).unwrap();
    config.insert("repositories".into(), Value::Table(repositories)).unwrap();

    let config_content = Value::Table(config);
    let toml_string = toml::to_string_pretty(&config_content).unwrap();

    std::fs::write(config_dir, toml_string).unwrap();
}
