use std::{
    env,
    fs::{self, File},
    path::PathBuf,
    process::{ExitCode, exit},
};
use toml::{Value, map::Map};

#[cfg(any(target_os = "macos", target_os = "linux"))]
pub const DEFAULT_PREFIX: &str = "/opt/packit/test";

#[cfg(target_os = "windows")]
pub const DEFAULT_PREFIX: &str = "C:\\Program Files\\packit\\test";

#[cfg(target_os = "linux")]
pub const DEFAULT_CONFIG_DIR: &str = "/etc/packit";

#[cfg(target_os = "macos")]
pub const DEFAULT_CONFIG_DIR: &str = "/Library/Application Support/packit";

#[cfg(target_os = "windows")]
pub const DEFAULT_CONFIG_DIR: &str = "C:\\Program Files\\packit";

/// Contains the necessary information for the cleanup.
struct Cleanup {
    existing_config: bool,
    prefix: PathBuf,
}

impl Cleanup {
    /// Cleans up after the tests.
    pub fn clean(&self) {
        println!("Running cleanup");

        // Only remove the config if it was auto-generated
        let config_dir = PathBuf::from(DEFAULT_CONFIG_DIR).join("TestConfig.toml");
        if !self.existing_config {
            if let Err(e) = fs::remove_file(config_dir) {
                eprintln!("Failed to remove 'TestConfig.toml'");
                eprintln!("Error: {e}");
                exit(1);
            }
        }

        // Remove the test prefix
        if let Err(e) = fs::remove_dir_all(&self.prefix) {
            eprintln!("Failed to remove test prefix '{}'", self.prefix.display());
            eprintln!("Error: {e}");
            exit(1);
        }

        println!("Running cleanup successful");
    }
}

// Implement drop to make sure the cleanup is still ran, even if a test panics
impl Drop for Cleanup {
    fn drop(&mut self) {
        self.clean();
    }
}

/// Wraps around the `cargo test` command to handle the setup and cleanup.
/// Returns an `ExitCode`.
fn main() -> ExitCode {
    // Execute setup, which will partially determine how the cleanup
    let _cleanup = setup();

    // Gather command arguments, and pass them to cargo test (the first argument is the program name)
    let args: Vec<String> = env::args().skip(1).collect();

    let status = std::process::Command::new("cargo")
        .args(["test", "--features", "test-support", "--", "--test-threads=1"])
        .args(args)
        .status()
        .expect("failed to run cargo test");

    ExitCode::from(status.code().unwrap_or(1) as u8)
}

/// Handles the test setup. Creates the `TestConfig.toml` if necessary and a new test prefix.
/// Returns `Cleanup` containing setup info.
fn setup() -> Cleanup {
    let mut existing_config = true;
    let config_dir = PathBuf::from(DEFAULT_CONFIG_DIR).join("TestConfig.toml");
    match fs::exists(&config_dir) {
        Ok(exists) if !exists => {
            println!("Using autogenerated 'TestConfig.toml'");
            create_default_test_config(&config_dir);
            existing_config = false;
        },
        Ok(_) => {},
        Err(e) => {
            eprintln!("Failed to check existence of '{}'", config_dir.display());
            eprintln!("Error: {e}");
            exit(1);
        },
    }

    // Get test config content
    let config_content = match fs::read_to_string(&config_dir) {
        Ok(content) => content,
        Err(e) => {
            eprintln!("Failed to read '{}'", config_dir.display());
            eprintln!("Error: {e}");
            exit(1);
        },
    };

    let config_content: Value = match toml::from_str(&config_content) {
        Ok(content) => content,
        Err(e) => {
            eprintln!("Failed to parse as toml file:\n'{config_content}'\n");
            eprintln!("Error: {e}");
            exit(1);
        },
    };

    let Some(config_content) = config_content.as_table() else {
        eprintln!("Failed to extract table from config file with the following content:\n'{config_content}'\n");
        exit(1);
    };

    // Get the test prefix
    let Some(prefix) = config_content.get("prefix_directory") else {
        eprintln!("Couldn't find 'prefix_directory' in 'TestConfig.toml'");
        exit(1);
    };

    let Some(prefix) = prefix.as_str() else {
        eprintln!("Invalid string value for 'prefix_directory' in 'TestConfig.toml'");
        exit(1);
    };

    let prefix = PathBuf::from(prefix);
    let register_directory = prefix.join("Register.toml");
    println!("Using prefix: {}", prefix.display());

    if fs::exists(&prefix).unwrap() {
        println!("Test prefix '{}' specified in 'TestConfig.toml' already exists", prefix.display());
        exit(1);
    }

    // Return an error if the prefix already exists, this could mean it's a 'normal' Packit prefix
    match fs::exists(&prefix) {
        Ok(exists) if exists => {
            println!("Test prefix '{}' specified in 'TestConfig.toml' already exists", prefix.display());
            exit(1);
        },
        Ok(_) => {},
        Err(e) => {
            eprintln!("Failed to check existence of '{}'", prefix.display());
            eprintln!("Error: {e}");
            exit(1);
        },
    }

    if let Err(e) = fs::create_dir_all(&prefix) {
        eprintln!("Failed to create test prefix '{}'", prefix.display());
        eprintln!("Error: {e}");
        exit(1);
    }

    if let Err(e) = fs::write(&register_directory, "# DO NOT EDIT THIS FILE") {
        eprintln!("Failed to create test 'Register.toml' at '{}'", register_directory.display());
        eprintln!("Error: {e}");
        exit(1);
    }

    Cleanup { existing_config, prefix }
}

/// Creates the default test config.
fn create_default_test_config(config_dir: &PathBuf) {
    let Some(parent) = config_dir.parent() else {
        eprintln!("Couldn't get config directory parent");
        exit(1);
    };

    if let Err(e) = fs::create_dir_all(parent) {
        eprintln!("Failed to create directory '{}'", parent.display());
        eprintln!("Error: {e}");
        exit(1);
    }

    if let Err(e) = File::create(config_dir) {
        eprintln!("Failed to create 'TestConfig.toml' at '{}'", config_dir.display());
        eprintln!("Error: {e}");
        exit(1);
    }

    let mut config = Map::new();
    config.insert("repositories_rank".into(), Value::Array(vec!["test".into()]));
    config.insert("prefix_directory".into(), DEFAULT_PREFIX.into());

    let mut repositories = Map::new();
    let mut test_repository = Map::new();
    test_repository.insert(
        "url".into(),
        Value::String("https://raw.githubusercontent.com/pack-it/test-repository/main/".into()),
    );
    test_repository.insert("provider".into(), "web".into());

    repositories.insert("test".into(), Value::Table(test_repository));
    config.insert("repositories".into(), Value::Table(repositories));

    let config_content = Value::Table(config);
    let toml_string = match toml::to_string_pretty(&config_content) {
        Ok(string) => string,
        Err(e) => {
            eprintln!("Failed to create toml string from:\n{config_content}\n");
            eprintln!("Error: {e}");
            exit(1);
        },
    };

    if let Err(e) = std::fs::write(config_dir, &toml_string) {
        eprintln!("Failed to write the following to '{}':\n{toml_string}\n", config_dir.display());
        eprintln!("Error: {e}");
        exit(1);
    }
}
