REM Prevent commands from being shown
@echo off

set VERSION="0.0.1"
if %PROCESSOR_ARCHITECTURE%=="ARM64" (
    set CURRENT_OS="aarch64-pc-windows-msvc"
) else (
    set CURRENT_OS="x86_64-pc-windows-msvc"
)

REM TODO: Set correct links at release
set SOURCE_REPOSITORY_URL="https://github.com/pack-it/packit/archive/refs/tags/%VERSION%.tar.gz"
set SOURCE_PREBUILD_REPOSITORY_URL="https://github.com/pack-it/packit/archive/refs/tags/%VERSION%.tar.gz"

REM Determine the prefix and config directory
set PREFIX_DIR="C:\Program Files\packit"
set CONFIG_DIR="C:\Program Files\packit"

REM Go into the prefix directory 
mkdir -p %PREFIX_DIR%\packages\packit\%VERSION%\bin
cd %PREFIX_DIR%\packages\packit\%VERSION%\bin

REM Install Packit to the prefix directory 
curl --proto "=https" -sSf $SOURCE_PREBUILD_REPOSITORY_URL
if %errorlevel%==0 (
    tar -xf packit@0.0.1-0-$TARGET.tar.gz
    rm packit@0.0.1-0-$TARGET.tar.gz
) else (
    set /p answer=Retrieving prebuilds failed. Do you wish to build Packit from source? (Y/n)
    if %answer% = "n" || %answer% = "no" (
        echo "Canceling installation of Packit"
        exit /b 1
    )

    set RUSTUP_INSTALLED=0

    REM Make sure cargo exists before building Packit
    where cargo
    if %errorlevel%!=0 (
        set /p answer=Cargo is not installed, do you wish to install it to build Packit? (y/N)
        if %answer% = "n" || %answer% = "no" || %answer% = "" (
            echo "Canceling installation of Packit"
            exit /b 1
        )

        REM TODO: Install rustup

        REM Make sure that the rustup install was successful
        where cargo
        if %errorlevel%!=0 (
            echo "Installing rustup failed, canceling Packit installation"
            exit /b 1
        )

        set RUSTUP_INSTALLED=1
    )

    curl --proto "=https" -sSf %SOURCE_REPOSITORY_URL%
    tar -xf packit@%VERSION%-0-%TARGET%.tar.gz REM TODO: Target is different when installing source instead of prebuild
    del packit@%VERSION%-0-%TARGET%.tar.gz
    cargo build
    mkdir bin
    move .\target\release\packit bin
    rmdir /s .\target

    if %RUSTUP_INSTALLED% (
        set /p answer=You installed rustup to install Packit. This installation is not registered in Packit. Do you wish to uninstall it? (Y/n)
        if %answer% = "y" || %answer% = "yes" (
            echo "Uninstalling rustup"
            rustup self uninstall
        )
    )
)

mklink /D .\pit .\packitß

REM Go into prefix\bin
mkdir -p %PREFIX_DIR%\bin
cd %PREFIX_DIR%\bin

REM Create symlinks for Packit in bin
ln -s %PREFIX_DIR%/packages/packit/%VERSION%/bin/packit %PREFIX_DIR%/bin/packit
ln -s %PREFIX_DIR%/packages/packit/%VERSION%/bin/pit %PREFIX_DIR%/bin/pit

mklink /D %PREFIX_DIR%\bin\packit %PREFIX_DIR%\packages\packit\%VERSION%\bin\packit
mklink /D %PREFIX_DIR%\bin\pit %PREFIX_DIR%\packages\packit\%VERSION%\bin\pit

REM Create symlinks for Packit in /active
mkdir /D %PREFIX_DIR%/active/packit %PREFIX_DIR%/packages/packit/%VERSION%

REM Go into the prefix directory and create the Installed.toml with Packit
cd %PREFIX_DIR%
(
    echo # DO NOT EDIT THIS FILE
    echo
    echo [package.packit]
    echo symlinked = true
    echo active_version = "%VERSION%"
    echo description = "The universal package manager, designed to streamline the experience of installing packages on your system."
    echo homepage = "https://github.com/pack-it/packit"
    echo
    echo [package.packit."%VERSION%"]
    echo package_id = "packit@%VERSION%"
    echo license = "GPLv3"
    echo source_repository_provider = "web"
    echo source_repository_url = "%SOURCE_REPOSITORY_URL%"
    echo source_prebuild_repository_provider = "web"
    echo source_prebuild_repository_url = "%SOURCE_PREBUILD_REPOSITORY_URL%"
    echo install_path = "%PREFIX_DIR%\packages\packit\%VERSION%"
    echo revisions = []
) > Installed.toml


REM Go into the config directory and create the default config
mkdir -p %CONFIG_DIR%\packit
cd %CONFIG_DIR%\packit
(
    echo repositories_rank = ["core"]
    echo
    echo [repositories]
    echo
    echo [repositories.core]
    echo provider = "web"
    echo path = "https://raw.githubusercontent.com/pack-it/core/main/"
) > Config.toml
