#!/bin/sh

# Early exit in case of failure
set -euo pipefail

VERSION="0.0.1"
CURRENT_OS="$(uname -s)"

# Get the OS name
if [ $CURRENT_OS = "Darwin" ];
    CURRENT_OS_NAME = "apple-darwin"
else if [ $CURRENT_OS = "Linux" ];
    if [ echo "$(ldd --version)" | grep -q "musl" ]
        CURRENT_OS_NAME = "unknown-linux-musl"
    else if [ echo "$(ldd --version)" | grep -q "GLIBC" ]
        CURRENT_OS_NAME = "unknown-linux-gnu"
    else
        echo "Current platform unsupported, stopping install"
        exit 1
    fi
else
    echo "Current platform unsupported, stopping install"
    exit 1
fi

# Get the current architecture
if [ "$(uname -m)" = "aarch64" ] || [ "$(uname -m)" = "arm64" ];
    CURRENT_ARCH="aarch64"
else if [ "$(uname -m)" = "x86_64" ];
    CURRENT_ARCH="x86_64"
else
    echo "Current architecture unsupported, stopping install"
    exit 1
fi

# Create target
TARGET="$CURRENT_ARCH-$CURRENT_OS_NAME"

# TODO: Set correct links at release
SOURCE_REPOSITORY_URL="https://github.com/pack-it/packit/archive/refs/tags/$VERSION.tar.gz"
SOURCE_PREBUILD_REPOSITORY_URL="https://github.com/pack-it/packit/archive/refs/tags/$VERSION.tar.gz"

# Determine the prefix and config directory
PREFIX_DIR="/opt/packit"
if [ $CURRENT_OS = "Darwin" ]; then
    CONFIG_DIR="/Library/Application Support"
else
    CONFIG_DIR="/etc"
fi

# Go into the prefix directory 
mkdir -p $PREFIX_DIR/packages/packit/$VERSION/bin
cd $PREFIX_DIR/packages/packit/$VERSION/bin

# Install Packit to the prefix directory
curl --proto "=https" -sSf $SOURCE_PREBUILD_REPOSITORY_URL
if [ $? ]; then
    tar -xf packit@0.0.1-0-$TARGET.tar.gz
    rm packit@0.0.1-0-$TARGET.tar.gz
else
    echo "Retrieving prebuilds failed. Do you wish to build Packit from source? (Y/n)"
    read answer
    if ! { [ $answer = "y" ] || [ $answer = "" ] || [ $answer = "yes" ]; }; then
        echo "Canceling installation of Packit"
        exit(1)
    fi

    RUSTUP_INSTALLED=0

    # Make sure cargo exists before building Packit
    command -v cargo
    if [ !$? ]; then
        echo "Cargo is not installed, do you wish to install it to build Packit? (y/N)"
        read answer
        if ! { [ $answer = "y" ] || [ $answer = "yes" ]; }; then
            echo "Canceling installation of Packit"
            exit(1)
        fi

        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

        # Make sure that the rustup install was successful
        command -v cargo
        if [ !$? ]; then
            echo "Installing rustup failed, canceling Packit installation"
            exit(1)
        fi

        RUSTUP_INSTALLED=1
    fi

    curl --proto "=https" -sSf $SOURCE_REPOSITORY_URL
    tar -xf packit@0.0.1-0-$TARGET.tar.gz # TODO: Target is different when installing source instead of prebuild
    rm packit@0.0.1-0-$TARGET.tar.gz
    cargo build
    mkdir ./bin
    mv ./target/release/packit ./bin
    rm -r ./target

    if [ $RUSTUP_INSTALLED ]; then
        echo "You installed rustup to install Packit. This installation is not registered in Packit. Do you wish to uninstall it? (Y/n)"
        read answer

        if [ $answer = "y" ] || [ $answer = "yes" ]; then
            echo "Uninstalling rustup"
            rustup self uninstall
        fi
    fi
fi
ln -s ./packit ./pit

# Go into prefix/bin
mkdir -p $PREFIX_DIR/bin
cd -p $PREFIX_DIR/bin

# Create symlinks for Packit in /bin
ln -s $PREFIX_DIR/packages/packit/$VERSION/bin/packit $PREFIX_DIR/bin/packit
ln -s $PREFIX_DIR/packages/packit/$VERSION/bin/pit $PREFIX_DIR/bin/pit

# Create symlinks for Packit in /active
ln -s $PREFIX_DIR/packages/packit/0.0.1 $PREFIX_DIR/active/packit

# Go into the prefix directory and create the Installed.toml with Packit
cd $PREFIX_DIR
cat << EOF > Installed.toml
# DO NOT EDIT THIS FILE

[package.packit]
symlinked = true
active_version = "$VERSION"
description = "The universal package manager, designed to streamline the experience of installing packages on your system."
homepage = "https://github.com/pack-it/packit"

[package.packit."$VERSION"]
package_id = "packit@$VERSION"
license = "GPLv3"
source_repository_provider = "web"
source_repository_url = "$SOURCE_REPOSITORY_URL"
source_prebuild_repository_provider = "web"
source_prebuild_repository_url = "$SOURCE_PREBUILD_REPOSITORY_URL"
install_path = "$PREFIX_DIR/packages/packit/$VERSION"
revisions = []
EOF

# Go into the config directory and create the default config
mkdir -p $CONFIG_DIR/packit
cd $CONFIG_DIR/packit
cat << EOF > Config.toml
repositories_rank = ["core"]

[repositories]

[repositories.core]
provider = "web"
path = "https://raw.githubusercontent.com/pack-it/core/main/"
EOF

# On Linux, add /opt/packit/lib to the linker paths
if [ $CURRENT_OS = "Linux" ];
    sudo echo "$PREFIX_DIR" > /etc/ld.so.conf.d/packit.conf
fi
