#!/bin/sh
set -eu

VERSION="0.0.1"
CURRENT_OS="$(uname -s)"

# Get the OS name
if [ $CURRENT_OS = "Darwin" ]; then
    CURRENT_OS_NAME="apple-darwin"
elif [ $CURRENT_OS = "Linux" ]; then
    if echo "$(ldd --version)" | grep -q "musl"; then
        CURRENT_OS_NAME="unknown-linux-musl"
    elif echo "$(ldd --version)" | grep -q "GLIBC"; then
        CURRENT_OS_NAME="unknown-linux-gnu"
    else
        echo "Current platform unsupported, stopping install"
        exit 1
    fi
else
    echo "Current platform unsupported, stopping install"
    exit 1
fi

# Get the current architecture
if [ "$(uname -m)" = "aarch64" ] || [ "$(uname -m)" = "arm64" ]; then
    CURRENT_ARCH="aarch64"
elif [ "$(uname -m)" = "x86_64" ]; then
    CURRENT_ARCH="x86_64"
else
    echo "Current architecture unsupported, stopping install"
    exit 1
fi

# Create target
TARGET="$CURRENT_ARCH-$CURRENT_OS_NAME"

SOURCE_REPOSITORY_URL="https://github.com/pack-it/packit/releases/download/$VERSION/packit@$VERSION.tar.gz"
SOURCE_PREBUILD_REPOSITORY_URL="https://github.com/pack-it/packit/releases/download/$VERSION/packit@$VERSION-0-$TARGET"

# Determine the prefix and config directory
PREFIX_DIR="/opt/packit"
if [ $CURRENT_OS = "Darwin" ]; then
    CONFIG_DIR="/Library/Application Support/packit"
else
    CONFIG_DIR="/etc/packit"
fi

USERNAME=$(whoami)

# Go into the prefix directory
sudo mkdir -p "$PREFIX_DIR/packages/packit/$VERSION/bin"
sudo chmod -R 755 "$PREFIX_DIR"
sudo chown -R $USERNAME "$PREFIX_DIR"
cd "$PREFIX_DIR/packages/packit/$VERSION/bin"

# Install Packit to the prefix directory
if curl --proto "=https" -sSfL $SOURCE_PREBUILD_REPOSITORY_URL --output packit; then
    echo "Downloaded prebuild"
else
    echo "Retrieving prebuilds failed. Do you wish to build Packit from source? (Y/n)"
    read answer
    if [ $answer = "n" ] || [ $answer = "no" ]; then
        echo "Canceling installation of Packit"
        exit 1
    fi

    RUSTUP_INSTALLED=0

    # Make sure cargo exists before building Packit
    if ! command -v cargo >/dev/null 2>&1; then
        echo "Cargo is not installed, do you wish to install it to build Packit? (y/N)"
        read answer
        if [ $answer = "n" ] || [ $answer = "no" ] || [ $answer = "" ]; then
            echo "Canceling installation of Packit"
            exit 1
        fi

        curl --proto '=https' --tlsv1.2 -sSfL https://sh.rustup.rs | sh

        # Make sure that the rustup install was successful
        if ! command -v cargo >/dev/null 2>&1; then
            echo "Installing rustup failed, canceling Packit installation"
            exit 1
        fi

        RUSTUP_INSTALLED=1
    fi

    curl --proto "=https" -sSfL $SOURCE_REPOSITORY_URL --output packit@$VERSION.tar.gz
    tar -xf packit@$VERSION.tar.gz
    rm packit@$VERSION.tar.gz
    cd packit@$VERSION
    cargo build --release
    mv ./target/release/packit ..
    cd ..
    rm -r ./packit@$VERSION

    if [ $RUSTUP_INSTALLED -eq 1 ]; then
        echo "You installed rustup to install Packit. This installation is not registered in Packit. Do you wish to uninstall it? (Y/n)"
        read answer

        if [ $answer = "y" ] || [ $answer = "yes" ] || [ $answer = "" ]; then
            echo "Uninstalling rustup"
            rustup self uninstall
        fi
    fi
fi

chmod +x ./packit
ln -s ./packit ./pit

# Go into prefix/bin
mkdir -p $PREFIX_DIR/bin
cd $PREFIX_DIR/bin

# Create symlinks for Packit in /bin
ln -s $PREFIX_DIR/packages/packit/$VERSION/bin/packit $PREFIX_DIR/bin/packit
ln -s $PREFIX_DIR/packages/packit/$VERSION/bin/pit $PREFIX_DIR/bin/pit

# Create symlinks for Packit in /active
mkdir -p $PREFIX_DIR/active/
ln -s $PREFIX_DIR/packages/packit/$VERSION $PREFIX_DIR/active/packit

# Go into the prefix directory and create the Installed.toml with Packit
cd $PREFIX_DIR
cat << EOF > Installed.toml
# DO NOT EDIT THIS FILE

[package.packit]
symlinked = true
active_version = "$VERSION"
description = "The universal package manager, designed to streamline the experience of installing packages on your system."
homepage = "https://github.com/pack-it/packit"

[package.packit."$VERSION"]
package_id = "packit@$VERSION"
license = "GPLv3"
source_repository_provider = "web"
source_repository_url = "$SOURCE_REPOSITORY_URL"
source_prebuild_repository_provider = "web"
source_prebuild_repository_url = "$SOURCE_PREBUILD_REPOSITORY_URL"
install_path = "$PREFIX_DIR/packages/packit/$VERSION"
revisions = []
EOF

# Go into the config directory and create the default config
sudo mkdir -p "$CONFIG_DIR"
sudo chmod -R 755 "$CONFIG_DIR"
sudo chown -R $USERNAME "$CONFIG_DIR"
cd "$CONFIG_DIR"
cat << EOF > Config.toml
repositories_rank = ["core"]

[repositories]

[repositories.core]
provider = "web"
path = "https://raw.githubusercontent.com/pack-it/core/main/"
EOF

echo "Successfully installed Packit"
echo "Add $PREFIX_DIR/bin to your PATH by adding the command below to your shell (.bashrc or .zshrc):"
echo "export PATH=\"$PREFIX_DIR/bin:\$PATH\""
