use std::{
    fs::{self, File},
    path::PathBuf,
    process::exit,
    str::FromStr,
};
use toml::{Value, map::Map};

use tempfile::{TempDir, tempdir};

// Test constants
#[cfg(target_os = "linux")]
pub const DEFAULT_CONFIG_DIR: &str = "/etc/packit";

#[cfg(target_os = "macos")]
pub const DEFAULT_CONFIG_DIR: &str = "/Library/Application Support/packit";

#[cfg(target_os = "windows")]
pub const DEFAULT_CONFIG_DIR: &str = "C:\\Program Files\\packit";

/// Contains the test information about the test environment and how to clean it up.
pub struct Environment {
    pub _temp_directory: TempDir, // Never used, but kept to keep the temporary directory in scope, so it doesn't get removed
    test_directory: PathBuf,
}

impl Environment {
    fn new() -> Self {
        // Keep `temp_directory` in scope, so it doesn't get removed
        let temp_directory = tempdir().expect("Failed to create test directory");
        let test_directory = temp_directory.path().to_path_buf();
        Self {
            _temp_directory: temp_directory,
            test_directory,
        }
    }

    /// Creates a new `Environment` and calls setup.
    pub fn init() -> Self {
        let environment = Self::new();
        environment.setup();
        environment
    }

    pub fn setup(&self) {
        let mut url = String::from("https://raw.githubusercontent.com/pack-it/test-repository/main/");
        let mut provider = String::from("web");

        // Check if `TestConfig.toml` exists in the default config directory
        let test_config_dir = PathBuf::from_str(DEFAULT_CONFIG_DIR).expect("Expected valid default").join("TestConfig.toml");
        if let Ok(true) = fs::exists(&test_config_dir) {
            println!("Using TestConfig.toml");

            let config_table = self.get_config_table(&test_config_dir);
            if let Some(config_url) = config_table.get("url") {
                url = config_url.to_string().trim_matches('"').to_string();
                dbg!(&url);
            }

            if let Some(config_provider) = config_table.get("provider") {
                provider = config_provider.to_string().trim_matches('"').to_string();
                dbg!(&provider);
            }
        }

        self.create_test_config(&url, &provider);

        // Create the `Register.toml`
        let register_file = self.test_directory.join("Register.toml");
        if let Err(e) = fs::write(&register_file, "# DO NOT EDIT THIS FILE") {
            eprintln!("Failed to create test 'Register.toml' at '{}'", register_file.display());
            eprintln!("Error: {e}");
            exit(1);
        }

        // Set the `PACKIT_CONFIG_DIR` environment variable
        unsafe {
            std::env::set_var("PACKIT_CONFIG_DIR", self.test_directory.clone());
        }
    }

    /// Gets the config table from the given config path.
    fn get_config_table(&self, config_path: &PathBuf) -> Map<String, Value> {
        let config_content = match fs::read_to_string(&config_path) {
            Ok(content) => content,
            Err(e) => {
                eprintln!("Failed to read '{}'", config_path.display());
                eprintln!("Error: {e}");
                exit(1);
            },
        };

        let config_content: Value = match toml::from_str(&config_content) {
            Ok(content) => content,
            Err(e) => {
                eprintln!("Failed to parse as toml file:\n'{config_content}'\n");
                eprintln!("Error: {e}");
                exit(1);
            },
        };

        let Some(config_content) = config_content.as_table() else {
            eprintln!("Failed to extract table from config file with the following content:\n'{config_content}'\n");
            exit(1);
        };

        config_content.clone()
    }

    /// Creates the test config.
    fn create_test_config(&self, repository_url: &str, repository_provider: &str) {
        let config_dir = self.test_directory.join("Config.toml");
        if let Err(e) = File::create(&config_dir) {
            eprintln!("Failed to create 'Config.toml' at '{}'", config_dir.display());
            eprintln!("Error: {e}");
            exit(1);
        }

        let mut config = Map::new();
        config.insert("repositories_rank".into(), Value::Array(vec!["test".into()]));
        config.insert("prefix_directory".into(), self.test_directory.display().to_string().into());

        let mut repositories = Map::new();
        let mut test_repository = Map::new();
        test_repository.insert("url".into(), Value::String(repository_url.into()));
        test_repository.insert("provider".into(), repository_provider.into());

        repositories.insert("test".into(), Value::Table(test_repository));
        config.insert("repositories".into(), Value::Table(repositories));

        let config_content = Value::Table(config);
        let toml_string = match toml::to_string_pretty(&config_content) {
            Ok(string) => string,
            Err(e) => {
                eprintln!("Failed to create toml string from:\n{config_content}\n");
                eprintln!("Error: {e}");
                exit(1);
            },
        };

        dbg!("Final test config:");
        dbg!(&toml_string);

        if let Err(e) = std::fs::write(&config_dir, &toml_string) {
            eprintln!("Failed to write the following to '{}':\n{toml_string}\n", config_dir.display());
            eprintln!("Error: {e}");
            exit(1);
        }
    }

    /// Cleans up after the tests.
    pub fn clean(&self) {
        println!("Running cleanup");

        if self.test_directory.exists() {
            println!("Test directory already cleaned");
            return;
        }

        // Remove the test directory
        if let Err(e) = fs::remove_dir_all(&self.test_directory) {
            eprintln!("Failed to remove test directory'{}'", self.test_directory.display());
            eprintln!("Error: {e}");
            exit(1);
        }

        println!("Running cleanup successful");
    }
}

// Implement drop to make sure the cleanup is still ran, even if a test panics
impl Drop for Environment {
    fn drop(&mut self) {
        self.clean();
    }
}
