use std::{
    collections::{HashMap, HashSet},
    fs,
    path::{Path, PathBuf},
};

use serde::{Deserialize, Serialize};

use crate::{
    config::{self, Repository},
    installer::types::{Dependency, PackageId, Version},
    platforms::{DEFAULT_CONFIG_DIR, TARGET_ARCHITECTURE},
    repositories::types::{PackageMetadata, PackageVersion},
    storage::error::InstalledPackagesError,
    utils::constants::INSTALLED_FILENAME,
};

const HEADER_TEXT: &str = "# DO NOT EDIT THIS FILE";

/// Represents the file which stores the installed packages.
#[derive(Serialize, Deserialize, Debug)]
pub struct InstalledPackageStorage {
    #[serde(rename = "package")]
    pub installed_packages: HashMap<PackageId, InstalledPackageVersion>,
}

/// Represents a package which is installed on the system.
#[derive(Serialize, Deserialize, Debug)]
pub struct InstalledPackageVersion {
    pub package_id: PackageId,
    pub description: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub homepage: Option<String>,
    pub source_repository_url: String,

    #[serde(default = "config::default_repository_provider")]
    #[serde(skip_serializing_if = "is_repository_provider_default")]
    pub source_repository_provider: String,

    #[serde(default)]
    #[serde(skip_serializing_if = "HashSet::is_empty")]
    pub dependencies: HashSet<PackageId>,

    #[serde(default)]
    #[serde(skip_serializing_if = "HashSet::is_empty")]
    pub dependents: HashSet<PackageId>,

    pub install_path: PathBuf,
    pub symlinked: bool,
}

fn is_repository_provider_default(value: &String) -> bool {
    *value == config::default_repository_provider()
}

impl InstalledPackageStorage {
    /// Loads the installed packages file from the given path.
    ///
    /// # Errors
    ///
    /// This function will return an error if the file cannot be opened or if the content is invalid.
    pub fn from(path: &Path) -> Result<Self, InstalledPackagesError> {
        // If the file does not exist, we return an empty storage
        if !fs::exists(path)? {
            return Ok(InstalledPackageStorage {
                installed_packages: HashMap::new(),
            });
        }

        // Read data from file
        let file_content = fs::read_to_string(path)?;

        // If the file is empty, return an empty storage
        if file_content.trim().is_empty() {
            return Ok(InstalledPackageStorage {
                installed_packages: HashMap::new(),
            });
        }

        // Parse data and return
        Ok(toml::from_str(&file_content)?)
    }

    /// Adds a package to the storage.
    /// Please note that this does not save the storage and does not read the currently installed packages from the toml.
    pub fn add_package(
        &mut self,
        package: &PackageMetadata,
        package_version: &PackageVersion,
        source_repository: &Repository,
        install_path: &PathBuf,
        symlinked: bool,
    ) {
        // TODO: Check if it's possible to pass the dependency ids instead
        // Add global and target specific dependencies
        let dependencies: Vec<&Dependency> = match package_version.targets.get(TARGET_ARCHITECTURE) {
            Some(target) => package_version.dependencies.iter().chain(target.dependencies.iter()).collect(),
            None => package_version.dependencies.iter().collect(),
        };

        // Get the satisfying package for the dependencies
        let mut dependency_ids = HashSet::new();
        for dependency in dependencies {
            if let Some(package) = self.get_satisfying_package(dependency) {
                dependency_ids.insert(package.package_id.clone());
            }
        }

        let installed_package = InstalledPackageVersion {
            package_id: PackageId::new(&package.name, &package_version.version),
            description: package.description.clone(),
            homepage: package.homepage.clone(),
            source_repository_url: source_repository.path.clone(),
            source_repository_provider: source_repository.provider.clone(),
            dependencies: dependency_ids,
            dependents: HashSet::new(),
            install_path: install_path.into(),
            symlinked,
        };

        // Add the package as a dependent in its dependencies
        for dependency in &installed_package.dependencies {
            if let Some(package) = self.get_package_mut(&dependency) {
                package.dependents.insert(installed_package.package_id.clone());
            }
        }

        self.installed_packages.insert(PackageId::new(&package.name, &package_version.version), installed_package);
    }

    /// Removes a package version from the info storage.
    /// Please note that this does not save the storage and does not read the currently installed packages from the toml.
    pub fn remove_package_version(&mut self, package_id: &PackageId) {
        self.installed_packages.remove(package_id);

        // Remove the package as a dependent of other remaining packages
        // TODO: Look for a way to only loop over dependencies to delete dependents
        for installed_package in self.installed_packages.values_mut() {
            installed_package.dependents.remove(package_id);
        }
    }

    /// Removes an entire package from the info storage
    /// Please note that this does not save the storage and does not read the currently installed packages from the toml.
    pub fn remove_package(&mut self, package_name: &str) {
        // Get all package version ids
        // TODO: look at clone
        let package_ids: Vec<PackageId> = self.get_package_versions(package_name).iter().map(|p| p.package_id.clone()).collect();

        for package_id in package_ids {
            self.remove_package_version(&package_id);
        }
    }

    /// Gets all installed versions of a certain package from the storage.
    /// Returns a list containing all installed versions, which is empty if the package is not installed.
    /// TODO: maybe create something which knows all package versions installed for a particular package
    pub fn get_package_versions(&self, package_name: &str) -> Vec<&InstalledPackageVersion> {
        let mut result = Vec::new();

        for package in self.installed_packages.values() {
            if package.package_id.name == package_name {
                result.push(package);
            }
        }

        result
    }

    pub fn package_version_exists(&self, package_id: &PackageId) -> bool {
        self.get_package(package_id).is_some()
    }

    /// Checks if a given package is symlinked, if the package doesn't exist false is returned (since it's not symlinked).
    pub fn package_is_symlinked(&self, package_id: &PackageId) -> bool {
        match self.get_package(package_id) {
            Some(package) => package.symlinked,
            None => false,
        }
    }

    /// Checks if a certain package is a dependency by checking its dependents.
    /// If only a package name is given we check all installed versions of that
    /// package, if any of those are a dependency we return true.
    pub fn is_dependency(&self, package_name: &str, version: Option<&Version>) -> bool {
        if let Some(version) = version {
            return match self.get_package(&PackageId::new(package_name, version)) {
                Some(package) => !package.dependents.is_empty(),
                None => false, // If the package doesn't exist it's not a dependency
            };
        }

        for package in self.get_package_versions(package_name) {
            if !package.dependents.is_empty() {
                return true;
            }
        }

        false
    }

    /// Checks if the dependency is already satisfied.
    pub fn dependency_satisfied(&self, dependency: &Dependency) -> bool {
        self.get_satisfying_package(dependency).is_some()
    }

    /// Gets the installed package which statisfies the dependency.
    pub fn get_satisfying_package(&self, dependency: &Dependency) -> Option<&InstalledPackageVersion> {
        for package in self.installed_packages.values() {
            if dependency.satisfied(&package.package_id.name, Some(&package.package_id.version)) {
                return Some(package);
            }
        }

        None
    }

    /// Gets a specific version of a certain package from the storage.
    /// Returns the package version, or None if the package version is not installed.
    pub fn get_package(&self, package_id: &PackageId) -> Option<&InstalledPackageVersion> {
        self.installed_packages.get(package_id)
    }

    /// Gets a specific version of a certain package from the storage.
    /// Returns a mutable reference to the package version, or None if the package version is not installed.
    pub fn get_package_mut(&mut self, package_id: &PackageId) -> Option<&mut InstalledPackageVersion> {
        self.installed_packages.get_mut(package_id)
    }

    /// Saves the installed packages file to the given path.
    ///
    /// # Errors
    ///
    /// This function will return an error if the data cannot be serialized or if the file cannot be written.
    pub fn save_to(&self, path: &Path) -> Result<(), InstalledPackagesError> {
        let data = toml::to_string(self)?;

        // Add header text to data
        let data = format!("{HEADER_TEXT}\n\n{data}");

        // Convert string path to Path struct
        let path = Path::new(path);

        // Create parent directories
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }

        // Write data to file
        fs::write(path, data)?;

        Ok(())
    }

    /// Gets the default path of the Packit installed packages file.
    pub fn get_default_path() -> PathBuf {
        Path::new(DEFAULT_CONFIG_DIR).join(INSTALLED_FILENAME)
    }
}
