// SPDX-License-Identifier: GPL-3.0-only
use std::{
    collections::{HashMap, HashSet},
    fs,
    path::{Path, PathBuf},
};

use serde::{Deserialize, Serialize};

use crate::{
    cli::display::logging::warning,
    config::{Config, Repository},
    installer::types::{Dependency, OptionalPackageId, PackageId, PackageName},
    repositories::types::{PackageMeta, PackageVersionMeta},
    storage::{error::Result, installed_package::InstalledPackage, installed_package_version::InstalledPackageVersion},
    utils::constants::REGISTER_FILENAME,
};

const HEADER_TEXT: &str = "# DO NOT EDIT THIS FILE";

/// Represents the register file, holding references to packages with package names.
#[derive(Deserialize, Serialize, Debug)]
pub struct PackageRegister {
    #[serde(rename = "package")]
    #[serde(skip_serializing_if = "HashMap::is_empty", default)]
    packages: HashMap<PackageName, InstalledPackage>,
}

impl PackageRegister {
    /// Loads the register file from the given path.
    ///
    /// # Errors
    ///
    /// This function will return an error if the file cannot be opened or if the content is invalid.
    pub fn from(path: &Path) -> Result<Self> {
        // If the file does not exist, we return an empty storage
        if !fs::exists(path)? {
            return Ok(PackageRegister { packages: HashMap::new() });
        }

        // Read data from file
        let file_content = fs::read_to_string(path)?;

        // If the file is empty, return an empty storage
        if file_content.trim().is_empty() {
            return Ok(PackageRegister { packages: HashMap::new() });
        }

        // Parse data and return
        Ok(toml::from_str(&file_content)?)
    }

    /// Saves the register file to the given path.
    ///
    /// # Errors
    ///
    /// This function will return an error if the data cannot be serialized or if the file cannot be written.
    pub fn save_to(&self, path: &Path) -> Result<()> {
        let data = toml::to_string(self)?;

        // Add header text to data
        let data = format!("{HEADER_TEXT}\n\n{data}");

        // Convert string path to Path struct
        let path = Path::new(path);

        // Create parent directories
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }

        // Write data to file
        fs::write(path, data)?;

        Ok(())
    }

    /// Gets the default path of the Packit installed packages file.
    pub fn get_default_path(config: &Config) -> PathBuf {
        Path::new(&config.prefix_directory).join(REGISTER_FILENAME)
    }

    /// Adds a package to the register storage.
    /// Please note that this does not save the storage and does not read the currently installed packages from the toml.
    pub fn add_package(
        &mut self,
        package: &PackageMeta,
        package_version: &PackageVersionMeta,
        dependency_ids: HashSet<PackageId>,
        source_repository: &Repository,
        install_path: &PathBuf,
        symlinked: bool,
        active: bool,
        used_prebuild: bool,
    ) -> Result<()> {
        let (source_prebuild_repository_url, source_prebuild_repository_provider) = match used_prebuild {
            true => (
                source_repository.prebuilds_url.clone(),
                source_repository.prebuilds_provider.clone(),
            ),
            false => (None, None),
        };

        let installed_package_version = InstalledPackageVersion {
            package_id: PackageId::new(package.name.clone(), package_version.version.clone()),
            license: package_version.license.clone(),
            source_repository_url: source_repository.path.clone(),
            source_repository_provider: source_repository.provider.clone(),
            source_prebuild_repository_url,
            source_prebuild_repository_provider,
            dependencies: dependency_ids,
            dependents: HashSet::new(),
            install_path: install_path.into(),
            revisions: package_version.revisions.clone(),
        };

        // Add the package as a dependent in its dependencies
        for dependency in &installed_package_version.dependencies {
            if let Some(package) = self.get_package_version_mut(&dependency) {
                package.dependents.insert(installed_package_version.package_id.clone());
            } else {
                warning!("Cannot retrieve package {dependency} from register to insert dependents");
            }
        }

        // Add the new installed package version and if there are no entries for the current package yet, also create a new entry
        match self.packages.get_mut(&package.name) {
            Some(package) => package.add_package_version(installed_package_version, active),
            None => {
                self.packages.insert(
                    package.name.clone(),
                    InstalledPackage::new(installed_package_version, symlinked, package),
                );
            },
        };

        Ok(())
    }

    /// Removes a package version from the register storage.
    /// Please note that this does not save the storage and does not read the currently installed packages from the toml.
    pub fn remove_package_version(&mut self, package_id: &PackageId) {
        // Get the package, if it doesn't exist return early.
        let package = match self.get_package_mut(&package_id.name) {
            Some(package) => package,
            None => return,
        };

        // Remove and get the package version, if it doesn't exist return early.
        let package_version = match package.versions.remove(&package_id.version) {
            Some(package_version) => package_version,
            None => return,
        };

        // Remove the package if it's empty after the removal of one package version
        if package.versions.is_empty() {
            self.packages.remove(&package_id.name);
        }

        // Loop through all the dependencies to delete the package from their dependents
        for dependency in package_version.dependencies {
            if let Some(dependency_version) = self.get_package_version_mut(&dependency) {
                dependency_version.dependents.remove(package_id);
            }
        }
    }

    /// Removes all package versions from the register storage.
    /// Please note that this does not save the storage and does not read the currently installed packages from the toml.
    pub fn remove_package(&mut self, package_name: &PackageName) {
        // Get all package version ids
        let package_ids: Vec<PackageId> = self.get_all_package_versions(package_name).iter().map(|p| p.package_id.clone()).collect();

        for package_id in package_ids {
            self.remove_package_version(&package_id);
        }
    }

    /// Gets references to all installed versions of a certain package from the register storage.
    /// Returns a list containing all installed versions, which is empty if the package is not installed.
    pub fn get_all_package_versions(&self, package_name: &PackageName) -> Vec<&InstalledPackageVersion> {
        match self.packages.get(package_name) {
            Some(package) => package.get_versions(),
            None => Vec::new(),
        }
    }

    /// Gets mutable references to all installed versions of a certain package from the register storage.
    /// Returns a list containing all installed versions, which is empty if the package is not installed.
    pub fn get_all_package_versions_mut(&mut self, package_name: &PackageName) -> Vec<&mut InstalledPackageVersion> {
        match self.packages.get_mut(package_name) {
            Some(package) => package.get_versions_mut(),
            None => Vec::new(),
        }
    }

    /// Gets a specific version of a certain package from the storage.
    /// Returns the package version, or None if the package version is not installed.
    pub fn get_package_version(&self, package_id: &PackageId) -> Option<&InstalledPackageVersion> {
        if let Some(package) = self.packages.get(&package_id.name) {
            return package.get_package_version(&package_id.version);
        }

        None
    }

    /// Gets a specific version of a certain package from the storage.
    /// Returns a mutable reference to the package version, or None if the package version is not installed.
    pub fn get_package_version_mut(&mut self, package_id: &PackageId) -> Option<&mut InstalledPackageVersion> {
        if let Some(package) = self.packages.get_mut(&package_id.name) {
            return package.get_package_version_mut(&package_id.version);
        }

        None
    }

    /// Gets a package, returns None if it doesn't exist.
    pub fn get_package(&self, package_name: &PackageName) -> Option<&InstalledPackage> {
        self.packages.get(package_name)
    }

    /// Gets a package mutably, returns None if it doesn't exist.
    pub fn get_package_mut(&mut self, package_name: &PackageName) -> Option<&mut InstalledPackage> {
        self.packages.get_mut(package_name)
    }

    /// Checks if a certain package is a dependency by checking its dependents.
    /// If only a package name is given we check all installed versions of that
    /// package, if any of those are a dependency we return true.
    pub fn is_dependency(&self, optional_id: &OptionalPackageId) -> bool {
        // Only check a specific package version if a version is provided
        if let Some(package_id) = optional_id.versioned() {
            return match self.get_package_version(&package_id) {
                Some(package) => !package.dependents.is_empty(),
                None => {
                    warning!("Package version not found in dependency check.");
                    false // If the package doesn't exist it's not a dependency
                },
            };
        }

        // Check all package versions for being a dependency
        for package in self.get_all_package_versions(&optional_id.name) {
            if !package.dependents.is_empty() {
                return true;
            }
        }

        false
    }

    /// Gets the latest installed package which statisfies the given dependency.
    pub fn get_latest_satisfying_package(&self, dependency: &Dependency) -> Option<&InstalledPackageVersion> {
        let mut latest: Option<&InstalledPackageVersion> = None;

        // Loop over all packages with the dependency name and check if they satisfy the dependency
        for package in self.packages.get(dependency.get_name())?.get_versions() {
            if !dependency.satisfied(&package.package_id.name, &package.package_id.version) {
                continue;
            }

            latest = match latest {
                Some(latest) if latest.package_id.version < package.package_id.version => Some(package),
                None => Some(package),
                _ => continue,
            };
        }

        latest
    }

    /// Returns an iterator, which iterates over all nested installed package version values.
    pub fn iterate_all(&self) -> impl Iterator<Item = &InstalledPackageVersion> {
        self.packages.values().flat_map(|p| p.versions.values())
    }
}

#[cfg(test)]
pub mod tests {
    use std::str::FromStr;

    use crate::installer::types::VersionIntervals;
    use crate::installer::types::dependency_tests::create_dependency;
    use crate::platforms::TargetArchitecture;
    use crate::repositories::types::{Checksum, Licenses, Source, Sources, TargetBounds};

    use super::*;

    fn create_package_version(
        package_id: PackageId,
        dependencies: HashSet<PackageId>,
        dependents: HashSet<PackageId>,
    ) -> InstalledPackageVersion {
        InstalledPackageVersion {
            package_id,
            license: Licenses::Unknown,
            source_repository_provider: "-".to_string(),
            source_repository_url: "-".to_string(),
            source_prebuild_repository_url: None,
            source_prebuild_repository_provider: None,
            dependencies,
            dependents,
            install_path: "-".into(),
            revisions: Vec::new(),
        }
    }

    fn create_package(package_versions: Vec<InstalledPackageVersion>) -> InstalledPackage {
        let active_version = package_versions[0].package_id.version.clone();
        let mut versions = HashMap::new();
        for package_version in package_versions {
            versions.insert(package_version.package_id.version.clone(), package_version);
        }

        InstalledPackage {
            versions,
            symlinked: true,
            active_version,
            description: "-".to_string(),
            homepage: None,
        }
    }

    fn create_register() -> PackageRegister {
        let package_a = PackageId::from_str("A@3.4.1").expect("Expected valid package id");
        let package_b = PackageId::from_str("B@2.72").expect("Expected valid package id");
        let package_c = PackageId::from_str("C@1.18.1").expect("Expected valid package id");
        let package_d = PackageId::from_str("D@2.5.4").expect("Expected valid package id");
        let package_e = PackageId::from_str("E@10.4").expect("Expected valid package id");
        let package_f5 = PackageId::from_str("F@5").expect("Expected valid package id");
        let package_f6 = PackageId::from_str("F@6").expect("Expected valid package id");

        let mut packages = HashMap::new();
        let package_versions = vec![create_package_version(
            package_a.clone(),
            HashSet::from([package_b.clone(), package_c.clone()]),
            HashSet::new(),
        )];
        packages.insert(package_a.name.clone(), create_package(package_versions));

        let package_versions = vec![create_package_version(
            package_b.clone(),
            HashSet::from([package_e.clone()]),
            HashSet::from([package_a.clone()]),
        )];
        packages.insert(package_b.name.clone(), create_package(package_versions));

        let package_versions = vec![create_package_version(
            package_c.clone(),
            HashSet::from([package_d.clone(), package_e.clone()]),
            HashSet::from([package_a.clone()]),
        )];
        packages.insert(package_c.name.clone(), create_package(package_versions));

        let package_versions = vec![create_package_version(
            package_d.clone(),
            HashSet::from([package_f5.clone()]),
            HashSet::from([package_c.clone()]),
        )];
        packages.insert(package_d.name.clone(), create_package(package_versions));

        let package_versions = vec![create_package_version(
            package_e.clone(),
            HashSet::new(),
            HashSet::from([package_b, package_c]),
        )];
        packages.insert(package_e.name, create_package(package_versions));

        let package_versions = vec![
            create_package_version(package_f5.clone(), HashSet::new(), HashSet::from([package_d])),
            create_package_version(package_f6, HashSet::new(), HashSet::new()),
        ];
        packages.insert(package_f5.name, create_package(package_versions));

        PackageRegister { packages }
    }

    fn create_package_meta(package_id: &PackageId) -> PackageMeta {
        let current_target_bounds =
            TargetBounds::from_str(&TargetArchitecture::current().to_string()).expect("Expected valid target bounds");

        let version_intervals = VersionIntervals::from_str(&format!("{}", package_id.version)).expect("Expected valid version intervals.");

        PackageMeta {
            name: package_id.name.clone(),
            description: "-".to_string(),
            homepage: None,
            versions: vec![package_id.version.clone()],
            supported_versions: HashMap::from([(current_target_bounds, version_intervals)]),
        }
    }

    fn create_package_version_meta(package_id: &PackageId) -> PackageVersionMeta {
        PackageVersionMeta {
            version: package_id.version.clone(),
            dependencies: Vec::new(),
            build_dependencies: Vec::new(),
            targets: HashMap::new(),
            sources: Sources::Single(Source {
                url: "-".to_string(),
                checksum: Checksum { sha256: [0; 32] },
                mirrors: Vec::new(),
                skip_unpack: false,
            }),
            license: Licenses::Unknown,
            skip_symlinking: false,
            script_args: HashMap::new(),
            use_version_specific_build: false,
            use_version_specific_preinstall: false,
            use_version_specific_postinstall: false,
            use_version_specific_test: false,
            use_version_specific_uninstall: false,
            revisions: Vec::new(),
        }
    }

    #[test]
    fn add_package() {
        let mut register = create_register();
        let package_id = PackageId::from_str("new_package@2.90").expect("Expected valid package id");
        let package_meta = create_package_meta(&package_id);
        let package_version_meta = create_package_version_meta(&package_id);
        let mut dependency_ids = HashSet::new();
        dependency_ids.insert(PackageId::from_str("B@2.72").expect("Expected valid package id"));

        register
            .add_package(
                &package_meta,
                &package_version_meta,
                dependency_ids,
                &Repository::new("-", "-"),
                &PathBuf::from("-"),
                false,
                false,
                false,
            )
            .expect("Expected successful package addition in test");

        let package = match register.get_package_version(&package_id) {
            Some(package) => package,
            None => panic!("Expected Some(InstalledPackageVersion (..)), got None"),
        };

        let package_b_id = PackageId::from_str("B@2.72").expect("Expected valid package id");
        let package_b = match register.get_package_version(&package_b_id) {
            Some(package) => package,
            None => panic!("Expected Some(InstalledPackageVersion (..)), got None"),
        };

        assert_eq!(package.package_id.name, package_id.name);
        assert_eq!(package.package_id.version, package_id.version);
        assert_eq!(package.dependencies.get(&package_b_id), Some(&package_b_id));
        assert_eq!(package_b.dependents.get(&package_id), Some(&package_id));
    }

    #[test]
    fn remove_package_version() {
        let mut register = create_register();

        let package_b = PackageId::from_str("B@2.72").expect("Expected valid package id");
        register.remove_package_version(&package_b);

        assert!(register.get_package_version(&package_b).is_none());

        // Check if package A still has B as a dependency (B shouldn't be removed)
        let package_a = PackageId::from_str("A@3.4.1").expect("Expected valid package id");
        assert!(register.get_package_version(&package_a).expect("Expected package A").dependencies.get(&package_b).is_some());

        // Check that B is deleted as a dependent
        let package_e = PackageId::from_str("E@10.4").expect("Expected valid package id");
        assert!(register.get_package_version(&package_e).expect("Expected package C").dependents.get(&package_b).is_none());
    }

    #[test]
    fn remove_package_version_one_of_two() {
        let mut register = create_register();
        let package_f5 = PackageId::from_str("F@5").expect("Expected valid package id");
        let package_f6 = PackageId::from_str("F@6").expect("Expected valid package id");
        register.remove_package_version(&package_f5);

        assert!(register.get_package_version(&package_f5).is_none());
        assert!(register.get_package_version(&package_f6).is_some());
    }

    #[test]
    fn remove_package() {
        let mut register = create_register();

        let package_f = PackageId::from_str("F@5").expect("Expected valid package id");
        register.remove_package(&package_f.name);
        assert!(register.get_package(&package_f.name).is_none());

        // Check if package D still has B as a dependency (B shouldn't be removed)
        let package_d = PackageId::from_str("D@2.5.4").expect("Expected valid package id");
        assert!(register.get_package_version(&package_d).expect("Expected package D").dependencies.get(&package_f).is_some());
    }

    #[test]
    fn is_dependency() {
        let register = create_register();

        let package_f5 = PackageId::from_str("F@5").expect("Expected valid package id");

        assert!(register.is_dependency(&package_f5.into()));
        assert!(register.is_dependency(&OptionalPackageId::from_str("F").expect("Expected valid package name")));
    }

    #[test]
    fn is_not_dependency() {
        let register = create_register();

        let package_f6 = PackageId::from_str("F@6").expect("Expected valid package id");
        assert!(!register.is_dependency(&package_f6.into()));

        let package_a = PackageId::from_str("A@3.4.1").expect("Expected valid package id");
        assert!(!register.is_dependency(&package_a.into()));
    }

    #[test]
    fn get_latest_satisfying_package() {
        let register = create_register();
        let package_a_id = PackageId::from_str("F@6").expect("Expected valid package id");
        let dependency = create_dependency("F", ">5");
        let package_a = register.get_package_version(&package_a_id).expect("Expected package F.");

        match register.get_latest_satisfying_package(&dependency) {
            Some(package) => assert_eq!(package.package_id, package_a.package_id),
            None => panic!("Expected Some(InstalledPackageVersion (..)), got None"),
        }
    }

    #[test]
    fn latest_satisfying_package_not_found() {
        let register = create_register();
        let dependency = create_dependency("A", ">3.4.1");

        assert!(register.get_latest_satisfying_package(&dependency).is_none());
    }
}
