use std::{
    collections::{HashMap, HashSet},
    fs,
    path::{Path, PathBuf},
};

use serde::{Deserialize, Serialize};

use crate::{
    config::Repository,
    installer::types::{Dependency, PackageId, Version},
    platforms::{DEFAULT_CONFIG_DIR, TARGET_ARCHITECTURE},
    repositories::types::{PackageMetadata, PackageVersion},
    storage::{error::InstalledPackagesError, installed_package::InstalledPackage, installed_package_version::InstalledPackageVersion},
    utils::constants::INSTALLED_FILENAME,
};

const HEADER_TEXT: &str = "# DO NOT EDIT THIS FILE";

/// The package register holds references to packages with package names.
#[derive(Deserialize, Serialize, Debug)]
pub struct PackageRegister {
    pub packages: HashMap<String, InstalledPackage>,
}

impl PackageRegister {
    /// Loads the register file from the given path.
    ///
    /// # Errors
    ///
    /// This function will return an error if the file cannot be opened or if the content is invalid.
    pub fn from(path: &Path) -> Result<Self, InstalledPackagesError> {
        // If the file does not exist, we return an empty storage
        if !fs::exists(path)? {
            return Ok(PackageRegister { packages: HashMap::new() });
        }

        // Read data from file
        let file_content = fs::read_to_string(path)?;

        // If the file is empty, return an empty storage
        if file_content.trim().is_empty() {
            return Ok(PackageRegister { packages: HashMap::new() });
        }

        // Parse data and return
        Ok(toml::from_str(&file_content)?)
    }

    /// Saves the register file to the given path.
    ///
    /// # Errors
    ///
    /// This function will return an error if the data cannot be serialized or if the file cannot be written.
    pub fn save_to(&self, path: &Path) -> Result<(), InstalledPackagesError> {
        let data = toml::to_string(self)?;

        // Add header text to data
        let data = format!("{HEADER_TEXT}\n\n{data}");

        // Convert string path to Path struct
        let path = Path::new(path);

        // Create parent directories
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }

        // Write data to file
        fs::write(path, data)?;

        Ok(())
    }

    /// Gets the default path of the Packit installed packages file.
    pub fn get_default_path() -> PathBuf {
        Path::new(DEFAULT_CONFIG_DIR).join(INSTALLED_FILENAME)
    }

    /// Adds a package to the register storage.
    /// Please note that this does not save the storage and does not read the currently installed packages from the toml.
    pub fn add_package(
        &mut self,
        package: &PackageMetadata,
        package_version: &PackageVersion,
        source_repository: &Repository,
        install_path: &PathBuf,
        symlinked: bool,
        active: bool,
    ) {
        // Add global and target specific dependencies
        let dependencies: Vec<&Dependency> = match package_version.targets.get(TARGET_ARCHITECTURE) {
            Some(target) => package_version.dependencies.iter().chain(target.dependencies.iter()).collect(),
            None => package_version.dependencies.iter().collect(),
        };

        // Get the satisfying package for the dependencies
        let mut dependency_ids = HashSet::new();
        for dependency in dependencies {
            if let Some(package) = self.get_satisfying_package(dependency) {
                dependency_ids.insert(package.package_id.clone());
            }
        }

        let installed_package_version = InstalledPackageVersion {
            package_id: PackageId::new(&package.name, &package_version.version),
            source_repository_url: source_repository.path.clone(),
            source_repository_provider: source_repository.provider.clone(),
            dependencies: dependency_ids,
            dependents: HashSet::new(),
            install_path: install_path.into(),
            symlinked,
            active,
        };

        // Add the package as a dependent in its dependencies
        for dependency in &installed_package_version.dependencies {
            if let Some(package) = self.get_package_mut(&dependency) {
                package.dependents.insert(installed_package_version.package_id.clone());
            }
        }

        // Add the new installed package version and if there are no entries for the current package yet, also create a new entry
        match self.packages.get_mut(&package.name) {
            Some(package) => package.add_package_version(installed_package_version),
            None => {
                self.packages.insert(package.name.clone(), InstalledPackage::new(installed_package_version, package));
            },
        }
    }

    /// Removes a package version from the register storage.
    /// Please note that this does not save the storage and does not read the currently installed packages from the toml.
    pub fn remove_package_version(&mut self, package_id: &PackageId) {
        // Remove and get the package, if it doesn't exist return early.
        let mut package = match self.packages.remove(&package_id.name) {
            Some(package) => package,
            None => return,
        };

        // Remove and get the package version, if it doesn't exist return early.
        let package_version = match package.versions.remove(&package_id.version) {
            Some(package_version) => package_version,
            None => return,
        };

        // Loop through all the dependencies to delete the package from their dependents
        for dependency in package_version.dependencies {
            if let Some(dependency_version) = self.get_package_mut(&dependency) {
                dependency_version.dependents.remove(package_id);
            }
        }
    }

    /// Removes all package versions from the register storage.
    /// Please note that this does not save the storage and does not read the currently installed packages from the toml.
    pub fn remove_package(&mut self, package_name: &str) {
        // Get all package version ids
        let package_ids: Vec<PackageId> = self.get_package_versions(package_name).iter().map(|p| p.package_id.clone()).collect();

        for package_id in package_ids {
            self.remove_package_version(&package_id);
        }
    }

    /// Gets references to all installed versions of a certain package from the register storage.
    /// Returns a list containing all installed versions, which is empty if the package is not installed.
    pub fn get_package_versions(&self, package_name: &str) -> Vec<&InstalledPackageVersion> {
        match self.packages.get(package_name) {
            Some(package) => package.get_versions(),
            None => Vec::new(),
        }
    }

    /// Gets mutable references to all installed versions of a certain package from the register storage.
    /// Returns a list containing all installed versions, which is empty if the package is not installed.
    pub fn get_package_versions_mut(&mut self, package_name: &str) -> Vec<&mut InstalledPackageVersion> {
        match self.packages.get_mut(package_name) {
            Some(package) => package.get_versions_mut(),
            None => Vec::new(),
        }
    }

    /// Gets a specific version of a certain package from the storage.
    /// Returns the package version, or None if the package version is not installed.
    pub fn get_package(&self, package_id: &PackageId) -> Option<&InstalledPackageVersion> {
        if let Some(package) = self.packages.get(&package_id.name) {
            return package.get_package_version(&package_id.version);
        }

        None
    }

    /// Gets a specific version of a certain package from the storage.
    /// Returns a mutable reference to the package version, or None if the package version is not installed.
    pub fn get_package_mut(&mut self, package_id: &PackageId) -> Option<&mut InstalledPackageVersion> {
        if let Some(package) = self.packages.get_mut(&package_id.name) {
            return package.get_package_version_mut(&package_id.version);
        }

        None
    }

    /// Checks if a certain package is a dependency by checking its dependents.
    /// If only a package name is given we check all installed versions of that
    /// package, if any of those are a dependency we return true.
    pub fn is_dependency(&self, package_name: &str, version: Option<&Version>) -> bool {
        // Only check a specific package version if a version is provided
        if let Some(version) = version {
            return match self.get_package(&PackageId::new(package_name, version)) {
                Some(package) => !package.dependents.is_empty(),
                None => false, // If the package doesn't exist it's not a dependency
            };
        }

        // Check all package versions for being a dependency
        for package in self.get_package_versions(package_name) {
            if !package.dependents.is_empty() {
                return true;
            }
        }

        false
    }

    /// Checks if the dependency is satisfied.
    pub fn dependency_satisfied(&self, dependency: &Dependency) -> bool {
        self.get_satisfying_package(dependency).is_some()
    }

    /// Gets an installed package which statisfies the dependency.
    pub fn get_satisfying_package(&self, dependency: &Dependency) -> Option<&InstalledPackageVersion> {
        // Loop over all packages with the dependency name and check if they satisfy the dependency
        for package in self.packages.get(dependency.get_name())?.get_versions() {
            if dependency.satisfied(&package.package_id.name, Some(&package.package_id.version)) {
                return Some(package);
            }
        }

        None
    }

    /// Returns an iterator, which iterates over all nested installed package version values.
    pub fn iterate_all(&self) -> impl Iterator<Item = &InstalledPackageVersion> {
        self.packages.values().flat_map(|p| p.versions.values())
    }
}
